version: "3.7"
services:
#    app:
#        container_name: one-day-one-quote-bot-app
#        build:
##            context: docker/app
#            dockerfile: docker/app/Dockerfile
##        command: python manage.py runserver 0.0.0.0:8000
#        volumes:
#            - ./:/app
#        restart: always
#        ports:
#            - "8000:8000"
##        env_file:
##            - ./.env.dev
#        depends_on:
#            - postgres

    postgres:
        container_name: postgres-14
        image: postgres:14.0-alpine
        restart: always
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        volumes:
            - postgres-volume:/var/lib/postgresql/data/
        ports:
            - "5432:5432"

volumes:
    postgres-volume: