services:
    app:
        container_name: bot-app
        build:
#            context: docker/development
            dockerfile: docker/production/bot-app.dockerfile
#        command: python3 main.py
        image: ${REGISTRY_ADDRESS}/${IMAGE_NAME_FOR_BOT}:${IMAGE_TAG}
        restart: always
        environment:
            - PROD=1
            - DATABASE=postgres
        env_file:
            - .env
            - .env.prod
        depends_on:
            - postgres

    postgres:
        container_name: postgres-14
        image: postgres:14.0-alpine
        restart: always
        env_file:
            - .env
            - .env.prod
#        environment:
#            POSTGRES_USER: ${DB_USER}
#            POSTGRES_PASSWORD: ${DB_PASS}
#            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres-volume:/var/lib/postgresql/data/
        ports:
            - "5432:5432"

volumes:
    postgres-volume: