services:
    app:
        container_name: bot-app
        image: ${REGISTRY_HOST}/${REGISTRY_ADDRESS}/${IMAGE_NAME_FOR_BOT}:${IMAGE_TAG}
        restart: always
        working_dir: /app
        environment:
            - PROD=1
            - DATABASE=postgres
            - TZ=Europe/Moscow
        volumes:
            - ./logs:/app/logs
        env_file:
            - .env
        depends_on:
            - postgres

    schedule-app:
        container_name: schedule-app
        image: ${REGISTRY_HOST}/${REGISTRY_ADDRESS}/${IMAGE_NAME_FOR_SCHEDULE_APP}:${IMAGE_TAG}
        restart: always
        environment:
            - PROD=1
            - DATABASE=postgres
            - TZ=Europe/Moscow
        volumes:
            - ./logs:/app/logs
        env_file:
            - .env
        depends_on:
            - postgres

    postgres:
        container_name: ${DB_HOST}
        image: postgres:14.0-alpine
        restart: always
        working_dir: /app
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres-volume:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        env_file:
            - .env

volumes:
    postgres-volume: